#!/usr/bin/env bash
# Produce a single-file, drop-in header from include/ctestprobe.h and
# src/ctestprobe.c. Consumers can then vendor one file into their tree
# and pick up the framework with:
#
#     #define CTP_IMPLEMENTATION
#     #include "ctestprobe.h"     // in exactly one .c/.cpp translation unit
#
# and, in every other translation unit, just:
#
#     #include "ctestprobe.h"
#
# Usage:
#     scripts/amalgamate.sh [OUTPUT]
# Defaults to single_include/ctestprobe.h.

set -euo pipefail

repo="$(cd "$(dirname "$0")/.." && pwd)"
out="${1:-$repo/single_include/ctestprobe.h}"
header="$repo/include/ctestprobe.h"
impl="$repo/src/ctestprobe.c"

if [ ! -f "$header" ] || [ ! -f "$impl" ]; then
    echo "amalgamate.sh: missing $header or $impl" >&2
    exit 1
fi

mkdir -p "$(dirname "$out")"

# The header is unchanged. The implementation is wrapped in
# #ifdef CTP_IMPLEMENTATION and stripped of its own #include
# "ctestprobe.h" (it becomes recursive at the point of inclusion).
{
    echo "/*"
    echo " * ctestprobe — single-file amalgamated header."
    echo " * Generated by scripts/amalgamate.sh from include/ctestprobe.h + src/ctestprobe.c."
    echo " * Do not edit — regenerate."
    echo " *"
    echo " * In exactly one translation unit:"
    echo " *     #define CTP_IMPLEMENTATION"
    echo " *     #include \"ctestprobe.h\""
    echo " */"
    echo
    # Hoist feature test macros to the top of the amalgamated file so
    # they take effect before any system header (via stddef.h / string.h
    # in the declarations block) locks the glibc feature guards. Without
    # this, CLOCK_MONOTONIC, fileno, strsignal, etc. become invisible on
    # Linux. macOS is more forgiving so this masks locally.
    echo "#if !defined(_POSIX_C_SOURCE) || _POSIX_C_SOURCE < 200809L"
    echo "#  undef _POSIX_C_SOURCE"
    echo "#  define _POSIX_C_SOURCE 200809L"
    echo "#endif"
    echo
    cat "$header"
    echo
    echo "#ifdef CTP_IMPLEMENTATION"
    # Strip the impl's own include of the header (recursive at this
    # point) and its own _POSIX_C_SOURCE define (now hoisted above).
    grep -v '^#include "ctestprobe.h"' "$impl" \
        | grep -v '^#define _POSIX_C_SOURCE '
    echo "#endif /* CTP_IMPLEMENTATION */"
} > "$out"

echo "wrote $out ($(wc -l < "$out") lines)"
