name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: 20.11.1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: sudo apt-get install -y gcc make

      - name: Build
        run: make

      - name: Package
        run: |
          make clean
          tar -czvf package.tar.gz --exclude='*docs*' --exclude='*.github*' --exclude='*examples*' --exclude='*tests*' --exclude='.gitignore' --exclude='LICENSE' *

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: package.tar.gz
